# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        pip install pytest
        pip install poetry
        pip install flake8
        pip install coverage
        pip install pytest-cov

    - name: Run tests
      run: pytest --cov=refactornci tests/test_dll.py tests/test_node.py
      working-directory: ./refactorNCI/

    - name: Run linter
      run: poetry run flake8
      working-directory: ./refactorNCI/
      continue-on-error: true

    - name: Run coverage
      run: coverage run -m pytest
      working-directory: ./refactorNCI/

    - name: Generate coverage report
      run: coverage report
      working-directory: ./refactorNCI/
