# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pytest
        pip install poetry
        pip install coverage
        pip install pytest-cov

    - name: Run tests
      run: pytest --cov=refactornci tests/test_dll.py tests/test_node.py
      working-directory: ./refactorNCI/refactornci/

    - name: Run linter
      run: poetry run flake8

    - name: Run coverage
      run: coverage run -m pytest

    - name: Generate coverage report
      run: coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: htmlcov
